### ISSUE TITLE
Add `Tags` attribute to timeseries in the query response

### ISSUE THREAD

**Issue by chengwang86** [spaceapegames/go-wavefront#10]
According to the wavefront API documentation, the query response of `GET /api/v2/chart/api` has the following definition of `tags`:
```
Timeseries {
label (string, optional): Label of this timeseries ,
host (string, optional): Source/Host of this timeseries ,
tags (object, optional): Tags (key-value annotations) of this timeseries ,
data (Array[Inline Model 1], optional): Data returned by this time series. This is returned as a list of points, where each point is represented as a two-element list with 1st element being the timestamp in epoch SECONDS and the 2nd element being the numeric value of the series at the timestamp
}
```

However, the current struct for Timeseries doesn't have  the `tags` attribute at all. See here https://github.com/spaceapegames/go-wavefront/blob/master/query.go#L87
```
// TimeSeries represents a single TimeSeries as returned by Wavefront
type TimeSeries struct {
	DataPoints []DataPoint `json:"data"`
	Label      string      `json:"label"`
	Host       string      `json:"host"`
}
```
Can I submit a PR to add `Tags` to the struct?
```
// TimeSeries represents a single TimeSeries as returned by Wavefront
type TimeSeries struct {
	DataPoints []DataPoint `json:"data"`
	Label      string      `json:"label"`
	Host       string      `json:"host"`
        Tags       map[string]string   `json:"tags"`
}
```
A wavefront engineer told me that they always store the key-value pair of tags as `strings`.

**Comment by louism517** [comment]
@chengwang86 

Yes, we'd be happy to accept a PR with this functionality. Thanks.

**Comment by chengwang86** [comment]
@louism517 

In addition, can I add two more features to my PR?

1. According to the API, 
```
QueryResult {
warnings (string, optional): The warnings incurred by this query ,
name (string, optional): The name of this query ,
query (string, optional): The query used to obtain this result ,
timeseries (Array[Timeseries], optional),
stats (StatsModel, optional),
events (Array[QueryEvent], optional),
granularity (integer, optional): The granularity of the returned results, in seconds
}
```

I would like to add `warnings` as an attribute to the queryResponse struct https://github.com/spaceapegames/go-wavefront/blob/master/query.go#L72
This will be helpful for debugging purposes. For example, sometiimes the returned `Timeseries` is empty and the `warnings` tell you the reason, even if the response.statuscode is still 200 (query succeeded).

2. The `Execute()` function (https://github.com/spaceapegames/go-wavefront/blob/master/query.go#L127) doesn't check the response statuscode. I want to update this function so that it returns an error with the response message as a string if the statuscode is not 200.

**Comment by louism517** [comment]
Those both sound like great ideas. Look forward to your PR.

**Comment by chengwang86** [comment]
@louism517 Here is my PR https://github.com/spaceapegames/go-wavefront/pull/11

I just noticed that the http statuscode was already handled properly in client.go. So I didn't make any changes to the `Execute()` function.

**Comment by chengwang86** [comment]
close it per PR #11
