### ISSUE TITLE
Request to become a contributor to this project.

### ISSUE THREAD

**Issue by bobleaux** [spaceapegames/go-wavefront#14]
Hi there. I am very much interested in becoming a contributor to this project. My organization would benefit greatly from having an open source Golang Wavefront client, and, rather than starting my own project, I would much rather leverage and contribute to an existing open source project. I've added a pull request for your review to add additional features to the dashboard component. Your consideration would be greatly appreciated. Thank you, Pablo Judd

**Comment by nathmclean** [comment]
Hi @pablojudd We're more than happy to have others contribute. I've just made one comment on #13

**Comment by bobleaux** [comment]
Thank you. I made the necessary changes.
