### ISSUE TITLE
Add HTML format support for Email Alert Targets 

### ISSUE THREAD

**Issue by sanoojm** [spaceapegames/go-wavefront#22]
isHtmlContent is an option in Email Alert Targets to add HTML boilerplate to the Email content. This option is by default disabled.

**Comment by sanoojm** [comment]
Related to https://github.com/spaceapegames/terraform-provider-wavefront/pull/39

**Comment by sanoojm** [comment]
Please merge: https://github.com/spaceapegames/go-wavefront/pull/21

**Comment by nathmclean** [comment]
Thanks for the PR - merged and released under `1.4.0`
